workflows:
  android-release:
    name: Android Release & Publish
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play # Define this group in Codemagic UI with GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        - android_signing # Define this group with CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/mapping/release/mapping.txt
    
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal # or 'production', 'alpha', 'beta'
        submit_as_draft: true
  ios-release:
    name: iOS Release & Publish
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials # Define with APP_STORE_CONNECT_ISSUER_ID, KEY_ID, PRIVATE_KEY
        - ios_signing # Define with CERTIFICATE_PRIVATE_KEY, PROVISIONING_PROFILE
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Pod install
        script: |
          find . -name "Podfile" -exec dir {} \;
          cd ios && pod install && cd ..

      - name: Build iOS Archive
        script: |
          flutter build ipa --release --export-options-plist=/usr/local/share/ios-export-options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - *.dsym.zip
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY # contents of .p8 file
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # release_notes: # Use metadata structure instead for multi-lang support

